name: Lint
on:
  push:
    branches:
      - '**'
      - '!production'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Link
        run: pnpm install
        env:
          SKIP_VALIDATION: true

      - name: Typecheck
        run: pnpm tsc --noEmit
